root: true
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  ecmaFeatures:
    jsx: true
plugins:
  - @typescript-eslint
  - react
  - react-hooks
  - react-refresh
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars': 
    - warn
    - argsIngnorePattern: '^_'
  '@typescript-eslint/no-explicit-any': 
    - warn
  